eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: provider1
          uri: lb://provider1
          predicates:
          - Path=/s1/**
        - id: provider2
          uri: lb://provider2
          predicates:
          - Path=/s2/**
